Repository bentobox-dev/bento-box, pull requests merged in 2021-01, with the labels that each got.

#9 feat(ci): Add automatic spellcheck on codebase to CI
  .codespellrc
  .github/workflows/ci.yaml
  makefile
  protos/bento/protos/ecs.proto
  protos/bento/protos/graph.proto
  protos/bento/protos/types.proto
  protos/bento/protos/values.proto
  sdk/requirements-dev.txt
  sim/CMakeLists.txt
Labels: ci

#11 feat(ci): Add caching of docker layers to speed up CI build of bentobox-sim container.
  .github/workflows/ci.yaml
  infra/docker/sim/Dockerfile
Labels: ci/cd

#10 feat(cd): Automate build and deployment of bentobox-sdk docs on Github Pages
  .github/workflows/cd.yaml
  .github/workflows/ci.yaml
  makefile
Labels: ci/cd

#7 feat(sdk): Add Graph Compiler to compile basic arithmetic expressions
  protos/bento/protos/ecs.proto
  protos/bento/protos/graph.proto
  protos/bento/protos/services.proto
  protos/bento/protos/values.proto
  sdk/bento/__init__.py
  sdk/bento/ecs/__init__.py
  sdk/bento/ecs/base.py
  sdk/bento/graph/__init__.py
  sdk/bento/graph/analyzers.py
  sdk/bento/graph/ast.py
  sdk/bento/graph/ecs.py
  sdk/bento/graph/linters.py
  sdk/bento/graph/plotter.py
  sdk/bento/graph/transforms.py
  sdk/bento/graph/value.py
  sdk/bento/value.py
  sdk/requirements-dev.txt
  sdk/requirements.txt
  sdk/setup.cfg
  sdk/setup.py
  sdk/tests/graph/test_analyzers.py
  sdk/tests/graph/test_compile.py
  sdk/tests/graph/test_ecs.py
  sdk/tests/graph/test_linters.py
  sdk/tests/graph/test_plotter.py
  sdk/tests/graph/test_transforms.py
  sdk/tests/test_value.py
  sim/CMakeLists.txt
Labels: bug, feature

#13 ci: Fix bentobox-sim build not properly taking advantage of Docker Layer caching
  infra/docker/sim/Dockerfile
  makefile
  sim/CMakeLists.txt
  sim/dependencies.cmake
Labels: bug, ci/cd

#19 ci: Add clang-format to Lint and Format bentobox-sim and Protobuf Definitions
  .clang-format
  .github/workflows/ci.yaml
  makefile
  protos/bento/protos/ecs.proto
  protos/bento/protos/graph.proto
  protos/bento/protos/references.proto
  protos/bento/protos/services.proto
  protos/bento/protos/sim.proto
  protos/bento/protos/types.proto
  protos/bento/protos/values.proto
  sim/include/component/pos1DComponent.h
  sim/include/component/pos2DComponent.h
  sim/include/component/textureComponent.h
  sim/include/ics.h
  sim/include/index/componentType.h
  sim/include/index/indexStore.h
  sim/include/system/render.h
  sim/lib/core/include/core/graphicsContext.h
  sim/lib/core/include/core/ics/compVec.h
  sim/lib/core/include/core/ics/component.h
  sim/lib/core/include/core/ics/componentSet.h
  sim/lib/core/include/core/ics/componentStore.h
  sim/lib/core/include/core/ics/util/composable.h
  sim/lib/core/include/core/ics/util/typeMap.h
  sim/lib/core/include/core/systemContext.h
  sim/lib/core/include/core/windowContext.h
  sim/lib/core/src/graphicsContext.cpp
  sim/lib/core/src/ics/compVec.test.cpp
  sim/lib/core/src/ics/component.test.cpp
  sim/lib/core/src/ics/componentStore.cpp
  sim/lib/core/src/ics/componentStore.test.cpp
  sim/lib/core/src/ics/util/composable.test.cpp
  sim/lib/core/src/ics/util/typeMap.test.cpp
  sim/lib/core/src/systemContext.test.cpp
  sim/lib/core/src/windowContext.cpp
  sim/src/index/componentType.test.cpp
  sim/src/main.cpp
  sim/src/main.test.cpp
  sim/src/system/render.cpp
Labels: ci/cd

#8 feat(sdk): Add ability to compile If statements and ternary expressions to graph
  makefile
  sdk/bento/graph/__init__.py
  sdk/bento/graph/analyzers.py
  sdk/bento/graph/ast.py
  sdk/bento/graph/ecs.py
  sdk/bento/graph/transforms.py
  sdk/bento/value.py
  sdk/requirements-dev.txt
  sdk/requirements.txt
  sdk/tests/graph/resources/expected_graph_arithmetic.yaml
  sdk/tests/graph/resources/expected_graph_arithmetic_multiple.yaml
  sdk/tests/graph/resources/expected_graph_ifelse.yaml
  sdk/tests/graph/resources/expected_graph_ternary.yaml
  sdk/tests/graph/test_analyzers.py
  sdk/tests/graph/test_compile.py
  sdk/tests/graph/test_ecs.py
  sdk/tests/graph/test_transforms.py
Labels: bug, feature, sdk

#21 ICS Entity Index
  sim/CMakeLists.txt
  sim/include/ics.h
  sim/include/index/componentTypeIndex.h
  sim/include/index/entityIndex.h
  sim/include/index/indexStore.h
  sim/lib/core/CMakeLists.txt
  sim/lib/core/include/core/ics/util/setIntersection.h
  sim/lib/core/src/ics/util/setIntersection.test.cpp
  sim/src/index/componentType.test.cpp
  sim/src/index/entity.test.cpp
  sim/src/system/render.cpp
Labels: engine, feature

#25 fix(doc): Fix SDK Documentation Rendering in existing SDK Docs
  makefile
  sdk/bento/graph/__init__.py
  sdk/bento/graph/ast.py
  sdk/bento/graph/ecs.py
  sdk/bento/graph/transforms.py
Labels: bug, docs

#14 feat(sdk): Preprocess AugAssign into separate Assignment and Binary Operation
  sdk/bento/graph/__init__.py
  sdk/bento/graph/ast.py
  sdk/bento/graph/preprocessors.py
  sdk/bento/graph/transforms.py
  sdk/tests/graph/test_preprocessors.py
Labels: feature, sdk

#26 feat: Setup GRPC networking between SDK and Sim Engine, Add End to End Tests
  .dockerignore
  .github/workflows/cd.yaml
  .github/workflows/ci.yaml
  .gitignore
  e2e/requirements-e2e.txt
  e2e/test_e2e.py
  infra/docker/sim/Dockerfile
  makefile
  protos/bento/protos/services.proto
  protos/grpc/health/v1/health.proto
  sdk/bento/client.py
  sdk/tests/test_client.py
  sim/CMakeLists.txt
  sim/cmake/GetGitRevisionDescription.cmake
  sim/cmake/GetGitRevisionDescription.cmake.in
  sim/cmake/dependencies.cmake
  sim/include/git.h.in
  sim/include/network/grpcServer.h
  sim/include/service/engineService.h
  sim/src/main.cpp
  sim/src/main.test.cpp
  sim/src/network/grpcServer.cpp
  sim/src/network/grpcServer.test.cpp
  sim/src/service/engineService.cpp
  sim/src/service/engineService.test.cpp
  sim/src/system/render.cpp
Labels: ci/cd, engine, feature, sdk

#24 Graph Interpreter
  sim/CMakeLists.txt
  sim/include/component/pos1DComponent.h
  sim/include/component/pos2DComponent.h
  sim/include/component/textureComponent.h
  sim/include/component/userComponent.h
  sim/include/ics.h
  sim/include/index/componentTypeIndex.h
  sim/include/interpreter/graphInterpreter.h
  sim/include/interpreter/operations.h
  sim/lib/core/src/ics/componentStore.cpp
  sim/src/component/userComponent.cpp
  sim/src/component/userComponent.test.cpp
  sim/src/ics.cpp
  sim/src/index/componentTypeIndex.cpp
  sim/src/index/componentTypeIndex.test.cpp
  sim/src/interpreter/graphInterpreter.cpp
  sim/src/interpreter/graphInterpreter.test.cpp
  sim/src/interpreter/operations.cpp
  sim/src/main.cpp
  sim/src/system/render.cpp
Labels: engine, feature
